stages:
  - test

.test: &test
  image: mcr.microsoft.com/playwright:v1.22.0-focal
  cache:
    - key:
        files:
          - package.json
      paths:
        - node_modules
    - key:
        files:
          - package.json
      paths:
        - node_modules
  script:
    - npm install
    - npx playwright install
    - node split.js | xargs npm run ci-test
  artifacts:
    name: "test-results-$CI_COMMIT_REF_NAME"
    expire_in: 8 weeks
    when: always
    paths:
      - test-results

test dev:
  stage: test
  parallel: 2
  environment: dev
  only:
    - master
  variables:
    INFURA_KEY: $E2E_INFURA_KEY
    USER_ENCRYPTED_PASSWORD: $E2E_TESTS_USER_ENCRYPTED_PASSWORD
    USER_PASSWORD: $E2E_TESTS_USER_PASSWORD
    METAMASK_RECOVERY: $E2E_TESTS_METAMASK_RECOVERY
    METAMASK_PASSWORD: $E2E_TESTS_METAMASK_PASSWORD
    METAMASK_PRIVATE_KEY: $E2E_TESTS_METAMASK_PRIVATE_KEY
  <<: *test
