name: Integration Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  integration-tests:
    name: Integration Tests
    env:
      METAMASK_RECOVERY: ${{ secrets.METAMASK_RECOVERY }}
      METAMASK_PASSWORD: ${{ secrets.METAMASK_PASSWORD }}
      METAMASK_PRIVATE_KEY: ${{ secrets.METAMASK_PRIVATE_KEY }}
      INFURA_KEY: ${{ secrets.INFURA_KEY }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      USER_ENCRYPTED_PASSWORD: ${{ secrets.USER_ENCRYPTED_PASSWORD }}
      E2E_CI: true
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 14.17
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm install
      - name: Install Playwright dependencies
        run: npx playwright install
      - name: Run E2E tests
        run: npm run ci-test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: my-artifact
          path: ./test-results

